### ISSUE TITLE
Need help with polyfill for IE

### ISSUE THREAD

**Issue by hillscottc** [SidKwok/template-rwb#35]
I'm trying to use this boilerplate for an internal project at work (Disney), but it fails for IE 11 with:
>     Object doesn't support property or method 'assign'

Seems to be a polyfill problem for the IE browser, but I am having trouble making it work with your config. Could you provide example of how to modify the webpack config for IE 11 polyfill? Would be GREATLY appreciated. Thanks!!

**Comment by hillscottc** [comment]
Ah, I figured it out myself.
```
$ npm install --save babel-polyfill
```
Then, in webpack.base.conf.js,
module.exports = {
```
    entry: {
        // app: './src/main.js'
        app: ['babel-polyfill', './src/main.js']
    },
```

**Comment by SidKwok** [comment]
It should work with IE 11 without any configuration, so I consider it is a bug. Thanks to report the issue! I will reopen this issue and close it after I fix the bug
