### ISSUE TITLE
使用antd自定义主题报错

### ISSUE THREAD

**Issue by cch6** [SidKwok/template-rwb#36]
.babelrc文件的plugins中增加以下内容时，会报错
["import", {
            "libraryName": "antd",
            "style": true
        }]

![image](https://user-images.githubusercontent.com/16448771/33117502-a4b4711a-cfa3-11e7-9eca-fca8442d97e1.png)

排查问题 应该是postcss-loader的问题，
注释掉build/utils.js中
loaders.push({ loader: 'postcss-loader' });
可以正常运行

顺便赞一个，感觉这个脚手架写的很厉害

**Comment by SidKwok** [comment]
你能把你自定义主题那段代码提供一下吗？我测试一下

**Comment by cch6** [comment]
其实 不需要自定义主题就会出现这个问题
按照antd的官方的步骤来，增加babel-plugin-import组件
![image](https://user-images.githubusercontent.com/16448771/33202028-d3c9f9f0-d135-11e7-9e8d-a6b0957c90a6.png)
里边的"style":"css" 改成true
像下边这样
.babelrc文件
   ` "plugins": [
        "transform-runtime",
        "transform-decorators-legacy", 
        ["import", {
            "libraryName": "antd",
            "style": true
        }]
    ],`
就会报错了

**Comment by SidKwok** [comment]
设置成css应该是没问题的 至于true为什么不行 我还得看看

**Comment by JzoNgKVO** [comment]
我在配置 stylus 的时候遇到了同样的报错。utils 里面把 `postcss-loader` 写在了其他 loader 后面，顺序错了。 @cch6  你的报错里面 ` less-loader` 在 `postcss-loader` 前面了。

```
// generate loader string to be used with extract text plugin
    function generateLoaders (loader, loaderOptions) {
        const loaders = [cssLoader];

        // enable postcss by default
        loaders.push({ loader: 'postcss-loader' });
        
        if (loader) {
            loaders.push({
                loader: loader + '-loader',
                options: Object.assign({}, loaderOptions, {
                    sourceMap: options.sourceMap
                })
            });
        }

        // Extract CSS when that option is specified
        // (which is the case during production build)
        if (options.extract) {
            return ExtractTextPlugin.extract({
                use: loaders
            });
        } else {
            return [{ loader: 'style-loader' }].concat(loaders);
        }
    }
```
把 postcss-loader 移到 css-loader 就好了。

**Comment by SidKwok** [comment]
可以提个pr让我看看吗？感谢

**Comment by SidKwok** [comment]
Solved by #38
