### ISSUE TITLE
javascript error when modifying HtmlWebpackPlugin

### ISSUE THREAD

**Issue by hillscottc** [SidKwok/template-rwb#37]
I'm working on a small internal project at Disney -- I could REALLY use some quick help, please! :)

I need to output an `index.asp` file along with the `index.html`

I made the following addition to webpack.prod.config, and added a file template...all fine.. 
```
      new HtmlWebpackPlugin({
            filename: 'index.asp',
            template: 'index.asp',
            inject: true,
            minify: {removeComments: true,collapseWhitespace: false, removeAttributeQuotes: false},
            chunksSortMode: 'dependency'
        }),
```
Output works. It spits out my `index.asp` file properly, with correctly injected resource links.

But the javascript throws top level error...
``` 
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at Ct (app.4df4f314a2b8e81a7a48.js:1) .....
```

Does something in the Chunking, or creating the Manifest, make it expect to be in a file named 'index.html'? Is that causing the error, perhaps? I hope you can help. Thanks, in advance.

**Comment by SidKwok** [comment]
Thanks. I will test this locally tonight and then fix.

**Comment by SidKwok** [comment]
I build it with `index.asp` (without any new code), but I can't find any `getAttribute` function in production `app.hash.js`. Did you add other thing in configuration files?

You can try to start a new project and build it with `index.asp` to see what's in `app.hash.js`.

```
sao rwb new-project -u
```

**Comment by hillscottc** [comment]
Ah, thanks for taking a look at it. And yes, with further testing, I found my mistake. I had an error in the .asp file I was using. I can see that it is working as it should. Thanks so much for your response! :)
