### ISSUE TITLE
我今天下载了你的模板，然后自己改了一下 改出问题来了 。你有没有qq什么的？我和你说一下我的问题

### ISSUE THREAD

**Issue by aKaigege** [SidKwok/template-rwb#39]

**Comment by aKaigege** [comment]
`patch.dev.js?c9a2:141 React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ Route() {
    var _temp, _this, _ret;

    _classCallCheck(this, Route);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key]…`

**Comment by aKaigege** [comment]
我的一直有这个警告 但是我的router 文件都是复制你的啊

**Comment by SidKwok** [comment]
请把改了的代码贴出来
