### ISSUE TITLE
开发服务器不支持低版本安卓

### ISSUE THREAD

**Issue by Jemair** [SidKwok/template-rwb#44]
在低版本安卓上通过ip访问开发服务器报错
具体从哪个机型开始报错没有仔细调查过
目前可以确认的是在4.4以下会报
```
WeakMap is not defined
```
在调试兼容性的时候造成了比较大的困难
目前的解决方式是先build到本地dist目录 然后使用servejs访问

另外之前的🌈色build log怎么没了hhh好失落

**Comment by SidKwok** [comment]
哈哈，🌈换了能看出打包细节的bar，各有喜好啦。

另外，安卓版本提供一下。

**Comment by Jemair** [comment]
话说大佬为什么要默认关掉cssModules   感觉开启cssModules才是开发react的正确姿势

**Comment by SidKwok** [comment]
这个问题是由于react-hot-reload的dev模式下没有编译，所以禁止掉相关的hot模块就好

App.jsx
```jsx
// import { hot } from 'react-hot-loader
// export default hot(module)(App)
export default App
```

webpack.dev.conf.js
```js
// Object.keys(baseWebpackConfig.entry).forEach(name => {
//     baseWebpackConfig.entry[name] = [
//         'react-hot-loader/patch',
//         './build/dev-client'
//     ].concat(baseWebpackConfig.entry[name]);
// });
```
